#开发环境
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://10.0.91.93:3306/mlzy?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #druid 配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,log4j
#redis配置
  redis:
    database: 0
    host: 10.0.91.82
    port: 6379
    password: root
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000